---
# Task to setup xfs gluster disk
# check for empty disk on either VMware or VirtualBox

  - name: creating new XFS disk
    filesystem: fstype={{ gluster_filesystem }} dev=/dev/{{ item.key }} opts="-i size=512"
    when: (item.value.model == "Virtual disk") and ((item.value.holders.0 is undefined) and (item.value.partitions|length < 1)) or
          (item.value.model == "VBOX HARDDISK") and ((item.value.holders.0 is undefined) and (item.value.partitions|count == 0))
    with_dict: "{{ ansible_devices }}"
    register: fs_action
    tags:
      - gluster-disks

  - name: tell me the key
    debug: msg={{ fs_action.results[-1].item.key }}

  - name: mounting GlusterFS brick filesystem
    mount: name={{ gluster_brick_dir }} src=/dev/{{ fs_action.results[-1].item.key }} fstype={{ gluster_filesystem }}
           opts=defaults,noatime,nobarrier
           dump=1
           passno=2
           state=mounted
    when: fs_action|succeeded
    tags:
      - gluster-mount
