---
# Task to install GlusterFS packages

    - name: Install and start glusterfs server
      yum: name={{ item }} state=installed
      with_items:
        - xfsprogs
        - glusterfs-server
        - glusterfs-client
      notify:
        - restart glusterd

    - service: name=glusterd state=started enabled=yes
