---
# Task to setup firewall (should be restricted in the future release)

    - name: iptables permit GlusterFS daemon
      service: name=iptables state=stopped enabled=no
      when: ansible_distribution_major_version == "6"

    - name: firewalld permit GlusterFS daemon
      service: name=firewalld state=stopped enabled=no
      when: ansible_distribution_major_version == "7"
